### ISSUE TITLE
Optional arguments for filter

### ISSUE THREAD

**Issue by janmartenjongerius** [johnnyfreeman/coseva#10]
Let filter accept optional arguments, which can be passed along to the filter using `call_user_func_array`.

Filter would become the following:

`public function filter (integer $column, [callable $callback, [mixed $arg1, [mixed $arg1, ...]]])`

Simply get a stack of the function arguments and shift the first and perhaps the second entry for getting both the column, if applicable, and the callback. Check if array shift returns a numeric or a callable. Let the remainder stay in the array and pass that along to the internal filter array.
### Psuedo code

``` php
<?php

$args = func_get_args();
$col = array_shift($args);

if (is_numeric($col)) {
  $callable = array_shift($args);
} else {
  $callable = $col;
  $col = null;
}

$this->_filters[] = array(
  'column' => $col,
  'callback' => $callback,
  'arguments' => $args
);
```

**Comment by johnnyfreeman** [comment]
So a filter could be written like this?

``` php
$csv->filter(function($row, $foo1, $foo2) {
    // do something
}, 'bar1', 'bar2');
```

Do you have a particular use-case in mind for this?

**Comment by janmartenjongerius** [comment]
A basic use case would be the conversion of foreign currencies. You could pass along the conversion rate for euros to dollars.

``` php
<?php

$conversion = 1.265;
$currency = 'USD';

$csv->filter(
  function (array $row, $conversion, $currency) {
    // Transform the currency.
    $row[3] *= $conversion;
    $row[4] = $currency;
    return $row;
  },
  $conversion,
  $currency
);
```

In the past I have used similar constructs to merge extensive datasets, reducing the iterations to a minimum.
