### ISSUE TITLE
Ability to specify separator

### ISSUE THREAD

**Issue by theduke** [johnnyfreeman/coseva#15]
CSV files often come with a bunch of separators.

Be it "," ";"  "|" or whatever.

One should be able to specify the separator for the parse method.

**Comment by johnnyfreeman** [comment]
Sounds good. Here's one way we could do it without changing much: http://www.php.net/manual/en/splfileobject.setcsvcontrol.php

**Comment by rebendajirijr** [comment]
Hi, could you tell us, when will you implement this feature request? I could change the class on myself, but that's not the way I'm looking for. Moreover, how about the licence? Is Coseva free for commerical use? Thx for answer.

JR

**Comment by johnnyfreeman** [comment]
@rebendajirijr Ask and you shall receive! Lol! And, Yes, you may use Coseva for commercial use.

Could you clone the [add-set-delimiter](https://github.com/johnnyfreeman/coseva/tree/add-set-delimiter) branch and let me know if it works for you? I'll wait until you get back with me to pull it into the master branch. Thanks!

**Comment by arjanvdbos** [comment]
Tested and works fine, please merge #18.
