### ISSUE TITLE
Documentation typos - certain instances of $row should be change to $column

### ISSUE THREAD

**Issue by antonsamper** [johnnyfreeman/coseva#19]
The documentation, README.md, has typos where in some cases the variable $row is being used when refering to a column. For example:

// delete 1st column
$csv->filter(function($row) {
    unset($row[0]);
    return $row;
});

Should be changed to:

// delete 1st column
$csv->filter(function($column) {
    unset($column[0]);
    return $column;
});

**Comment by johnnyfreeman** [comment]
Actually, in the example, you posted above:

``` php
// delete 1st column
$csv->filter(function($row) {
unset($row[0]);
return $row;
});
```

the entire row _is_ being passed to the closure here, not just one column. In other words, sometimes just one column is passed, and other times an array of columns is passed. It just depends on how you use the filter method. Passing an integer as the first parameter tells Coseva that you are looking for a particular column, so it will give you that particular column, If you only pass a closure (as above) then you are telling it that you want all the columns. So, maybe the documentation doesn't convey that well enough. Please correct me if I've misunderstood you. :)

And I like that you changed all the `$col` variables to `$column` as it is more explicit. I would even be fine with you changing all the `$row` variables to `$columns` for the same reason. Either way, it has to be shown that, in one case it is singular, and the other case it is plural.

**Comment by antonsamper** [comment]
yeah that makes sense, i'll change it now
