### ISSUE TITLE
Optimizing parse

### ISSUE THREAD

**Issue by janmartenjongerius** [johnnyfreeman/coseva#3]
There are a few performance issues and one general behavior issue with parse.
- Move `gc_collect_cycles()` to the end of the method. It is, by accident, placed at the end of each row iteration.
- Let `parse()` check if there are already rows present and iterate over available rows, rather than reparse the source file.
- Remove used filters, as they would not change the resultset for the better, but in stead could potentially corrupt the resultset.
- Let output methods like `toTable()` and the method `getIterator()` call `parse()` at least once when there are no rows present.

I will fix this issue myself.

@johnnyfreeman @johmanx10

**Comment by johnnyfreeman** [comment]
All this sounds good...

But instead of the `parse()` method simply checking whether the `_rows` property is `empty` or not, I think `parse()` should increment a "parsed counter" (or a "parsed boolean flag") and check that to decide whether to iterate over the `_rows` or the source. Because hypothetically a filter should be able to remove an entire row from the result set, which now that I think about it, I don't think it can as of right now.

What do you think @johmanx10?

**Comment by johnnyfreeman** [comment]
Also, the `toTable()`, `toJSON()`, and `getIterator()` methods would check this counter (or flag).

**Comment by janmartenjongerius** [comment]
Filters could at most simply not return anything at all. There is merit in your suggestion, but as I explicitely check this with `!isset($this->_rows)` instead of `empty($this->_rows)` and have changed the default value of `$this->_rows` to undefined, that would be no issue. Instead, if the CSV file were empty, It'd still recognize it as being parsed.

However, there is merit in adding a method `flushEmptyRows` as filters could remove rows in a whole, which you would potentially want to remove from your resultset. I do not advise to do this by default, as it will increase parse time.

Currently, I let the output methods also check against `!isset($this->_rows)` so again, there would be no guessing about whether or not `parse()` was actually called.

I also made sure that `parse()` will always at least set `$this->_rows` to an empty array. When that happens, it will return true on `isset()`.

**Comment by johnnyfreeman** [comment]
That works too. I wrote that before I saw your commits. :)
