### ISSUE TITLE
Flush NULL rows

### ISSUE THREAD

**Issue by janmartenjongerius** [johnnyfreeman/coseva#6]
Create a method to remove rows that have been filtered to oblivion. Suggested method: `flushEmptyRows()`

**Comment by johnnyfreeman** [comment]
Just a thought...

Would it be better to simply NOT save a row that has been filtered out? So something like this added to `parse()`:

``` php
foreach (new LimitIterator($this->_file, $rowOffset) as $key => $row)
{
    if (null !== $row = $this->_applyFilters($row)) {
        $this->_rows[$key] = $row;
    }
}
```

Or is there a benefit to coming back later and removing rows?

**Comment by janmartenjongerius** [comment]
Your suggestion would work, but:
- It increases parse time
- We probably don't want to alter the resultset in a manner that could deliver unexpected output to the user. For all we know, the user might want to use rows with `null` inside. For one thing, it would be really easy to create a diff that way.

### Diff example

``` php
<?php
$csv = CSV::getInstance('source.csv');

$original = (string) $csv;

$csv->filter(function(array $row) {
  if (!in_array($row[0], range(120, 136))) return $row;
});

$csv->parse();

$diff = (string) $csv;

$csv->flushEmptyRows();

$new = (string) $csv;
```
